---
title: "ES-среда"
author: "Romanov Stanislav"
date: "10 09 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Стандартная среда для ES-клеток

Рецепт, проверенный экспертами😀

```{r echo=FALSE}
blogdown::shortcode("notice","note" ,.content = "Чисто технически, можно заменить G-MEM на DMEM. В таком случае клетки не будут чувствовать себя хуже, но скорость роста несколько снизится.")
```

+--------------------------+---------------+--------------------------+
| Компонент                | 50 мл         | на 500мл банку среды     |
+==========================+===============+==========================+
| G-MEM                    | 43 мл         | 500 мл                   |
+--------------------------+---------------+--------------------------+
| GlutaMAX                 | 0.5 мл        | 0.58 мл                  |
+--------------------------+---------------+--------------------------+
| Sodium Pyruvate          | 0.5 мл        | 0.58 мл                  |
+--------------------------+---------------+--------------------------+
| MEM-NEAA                 | 0.5 мл        | 0.58 мл                  |
+--------------------------+---------------+--------------------------+
| Pen/Strep                | 0.5 мл        | 0.58 мл                  |
+--------------------------+---------------+--------------------------+
| ES-FBS                   | 5 мл          | 58 мл                    |
+--------------------------+---------------+--------------------------+
| 𝜷-меркаптоэтанол         | 100 мкл       | 1,16 мл                  |
+--------------------------+---------------+--------------------------+

```{r echo=FALSE}
blogdown::shortcode("notice","tip" ,.content = "После смешивания среду необходимо аликвотировать по 40-45 мл в фальконы на 50 и заморозить в вертикальном положении.")
```

```{r echo=FALSE}
blogdown::shortcode("notice","warning" ,.content = "Новоприготовленные стоки необходимо проверять на стерильность. Для этого необходимо налить 2-3 мл среды в 4-см чашку Петри и поставить в инкубатор на 2-3 дня. Если среда зарастет, то придется отфильтровать весь сток и снова проверить на зарост. Непроверенные среды лучше не использовать для культивирования ES-клеток.")
```

```{r echo=FALSE}
blogdown::shortcode("notice","note" ,.content = "После разморозки в фалькон со средой добавляем mLIF до концентрации 10pg/ml (Sigma) или 1000 U/ml (Gibco), пишем на банке \"+LIF\".")
```

```{r echo=FALSE}
blogdown::shortcode("notice","note" ,.content = "Если среда используется для культивирования без фидеров, то дополнительно добавляем CHIR до 3 мкМ и PD до 1 мкМ. В таком случае помечаем фалькон аббревиатурой \"2i\".")
```

```{r echo=FALSE}
blogdown::shortcode("notice","warning" ,.content = "После добавления LIF ES-среду уже нельзя замораживать! Если LIF подвергнется заморозке, то он потеряет способность стимулировать самообновление ES-клеток, в результате чего все колонии пойдут дифференцироваться.")
```
